In [ ]:
import pandas as pd
import numpy as np
import re
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("ambient-weather-June_2023.csv")

df.head()

Saving ambient-weather-June_2023.csv to ambient-weather-June_2023 (1).csv

,Date,Simple Date,Outdoor Temperature (°C),Feels Like (°C),Dew Point (°C),Wind Speed (m/sec),Wind Gust (m/sec),Max Daily Gust (m/sec),Wind Direction (°),Hourly Rain (mm/hr),...,Yearly Rain (mm),Relative Pressure (hPa),Humidity (%),Ultra-Violet Radiation Index,Solar Radiation (W/m^2),Outdoor Battery,Avg Wind Direction (10 mins) (°),Avg Wind Speed (10 mins) (m/sec),Indoor Battery,Absolute Pressure (hPa)
0,2023-06-30T23:55:00+05:30,2023-06-30 23:55:00,29.3,35.1,25.0,0.8,1.0,10.2,118,0.0,...,199.9,NaN,78,0,0.0,1,269,0.5,NaN,NaN
1,2023-06-30T23:50:00+05:30,2023-06-30 23:50:00,29.0,34.5,25.0,0.9,1.5,10.2,269,0.0,...,199.9,NaN,79,0,0.0,1,291,0.5,NaN,NaN
2,2023-06-30T23:45:00+05:30,2023-06-30 23:45:00,29.0,34.7,25.2,0.7,1.0,10.2,255,0.0,...,199.9,NaN,80,0,0.0,1,230,0.3,NaN,NaN
3,2023-06-30T23:40:00+05:30,2023-06-30 23:40:00,29.2,35.1,25.2,0.5,0.5,10.2,239,0.0,...,199.9,NaN,79,0,0.0,1,233,0.1,NaN,NaN
4,2023-06-30T23:35:00+05:30,2023-06-30 23:35:00,29.3,35.1,25.0,0.0,0.5,10.2,237,0.0,...,199.9,NaN,78,0,0.0,1,237,0.0,NaN,NaN

In [ ]:
import pandas as pd

# Select only numeric columns
numeric_df = df.select_dtypes(include='number')

# Check if any negative value exists
has_negative = (numeric_df < 0).any().any()

print("Negative values present:", has_negative)

Negative values present: False

In [ ]:
df.columns

Index(['Date', 'Simple Date', 'Outdoor Temperature (°C)', 'Feels Like (°C)',
       'Dew Point (°C)', 'Wind Speed (m/sec)', 'Wind Gust (m/sec)',
       'Max Daily Gust (m/sec)', 'Wind Direction (°)', 'Hourly Rain (mm/hr)',
       'Event Rain (mm)', 'Daily Rain (mm)', 'Weekly Rain (mm)',
       'Monthly Rain (mm)', 'Yearly Rain (mm)', 'Relative Pressure (hPa)',
       'Humidity (%)', 'Ultra-Violet Radiation Index',
       'Solar Radiation (W/m^2)', 'Outdoor Battery',
       'Avg Wind Direction (10 mins) (°)', 'Avg Wind Speed (10 mins) (m/sec)',
       'Indoor Battery', 'Absolute Pressure (hPa)'],
      dtype='object')

In [ ]:
# # Count non-null values per row
# row_non_nulls = df.notna().sum(axis=1)

# # Keep rows that have at least 20 values (out of 25)
# df_clean = df[row_non_nulls >= 20]

# print("Original rows:", df.shape[0])
# print("After cleaning:", df_clean.shape[0])

In [ ]:
# df_clean.columns

In [ ]:
def clean_date(date_str):
    if pd.isna(date_str):
        return np.nan

    # Remove timezone info like +05:30
    date_str = re.sub(r"\+\d{2}:\d{2}", "", str(date_str))

    # Replace 'T' with space
    date_str = date_str.replace("T", " ")

    return date_str.strip()

In [ ]:
df["Clean_Date"] = df["Date"].apply(clean_date)
df[["Date", "Clean_Date"]].head()

                        Date           Clean_Date
0  2023-06-30T23:55:00+05:30  2023-06-30 23:55:00
1  2023-06-30T23:50:00+05:30  2023-06-30 23:50:00
2  2023-06-30T23:45:00+05:30  2023-06-30 23:45:00
3  2023-06-30T23:40:00+05:30  2023-06-30 23:40:00
4  2023-06-30T23:35:00+05:30  2023-06-30 23:35:00

In [ ]:
df["Datetime"] = pd.to_datetime(
    df["Clean_Date"],
    errors="coerce",
    infer_datetime_format=True
)

df["Datetime"].isna().sum()

/tmp/ipython-input-3282131910.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["Datetime"] = pd.to_datetime(

np.int64(0)

In [ ]:
# df["Datetime"] = df["Datetime"].ffill().bfill()

In [ ]:
df = df.set_index("Datetime").sort_index()
df.head()

,Date,Simple Date,Outdoor Temperature (°C),Feels Like (°C),Dew Point (°C),Wind Speed (m/sec),Wind Gust (m/sec),Max Daily Gust (m/sec),Wind Direction (°),Hourly Rain (mm/hr),...,Relative Pressure (hPa),Humidity (%),Ultra-Violet Radiation Index,Solar Radiation (W/m^2),Outdoor Battery,Avg Wind Direction (10 mins) (°),Avg Wind Speed (10 mins) (m/sec),Indoor Battery,Absolute Pressure (hPa),Clean_Date
Datetime,,,,,,,,,,,,,,,,,,,,,
2023-06-01 00:01:00,2023-06-01T00:01:00+05:30,2023-06-01 00:01:00,28.8,34.5,25.4,0.0,0.5,0.5,245,0.0,...,NaN,82,0,0.0,1,245,0.0,NaN,NaN,2023-06-01 00:01:00
2023-06-01 00:06:00,2023-06-01T00:06:00+05:30,2023-06-01 00:06:00,28.9,34.9,25.5,0.0,0.5,0.5,173,0.0,...,NaN,82,0,0.0,1,245,0.0,NaN,NaN,2023-06-01 00:06:00
2023-06-01 00:10:00,2023-06-01T00:10:00+05:30,2023-06-01 00:10:00,28.9,35.1,25.7,0.0,0.5,0.5,222,0.0,...,NaN,83,0,0.0,1,214,0.0,NaN,NaN,2023-06-01 00:10:00
2023-06-01 00:15:00,2023-06-01T00:15:00+05:30,2023-06-01 00:15:00,28.9,35.3,25.9,0.1,0.5,0.5,177,0.0,...,NaN,84,0,0.0,1,183,0.0,NaN,NaN,2023-06-01 00:15:00
2023-06-01 00:20:00,2023-06-01T00:20:00+05:30,2023-06-01 00:20:00,28.9,35.1,25.7,0.0,0.0,0.5,173,0.0,...,NaN,83,0,0.0,1,177,0.0,NaN,NaN,2023-06-01 00:20:00

In [ ]:
# hourly_df = df.resample("H").mean(numeric_only=True)
# hourly_df.head()


# STEP 1: Count raw (5-minute) values per hour
hourly_count = df.resample("h").count()

# STEP 2: Compute hourly mean
hourly_mean = df.resample("h").mean(numeric_only=True)

# STEP 3: Keep values ONLY where raw data existed in that hour
hourly_df = hourly_mean.where(hourly_count > 0)

In [ ]:
full_hours = pd.date_range(
    start=hourly_df.index.min(),
    end=hourly_df.index.max(),
    freq="h"
)

hourly_df = hourly_df.reindex(full_hours)

In [ ]:
hourly_df = hourly_df.interpolate(method="time")

In [ ]:
hourly_df = hourly_df.reset_index()
hourly_df.rename(columns={"index": "Datetime"}, inplace=True)

hourly_df.head()

,Datetime,Outdoor Temperature (°C),Feels Like (°C),Dew Point (°C),Wind Speed (m/sec),Wind Gust (m/sec),Max Daily Gust (m/sec),Wind Direction (°),Hourly Rain (mm/hr),Event Rain (mm),...,Yearly Rain (mm),Relative Pressure (hPa),Humidity (%),Ultra-Violet Radiation Index,Solar Radiation (W/m^2),Outdoor Battery,Avg Wind Direction (10 mins) (°),Avg Wind Speed (10 mins) (m/sec),Indoor Battery,Absolute Pressure (hPa)
0,2023-06-01 00:00:00,28.825000,34.991667,25.741667,0.075000,0.416667,0.625,190.083333,0.0,0.0,...,0.0,NaN,83.583333,0.0,0.0,1.0,195.500000,0.000000,NaN,NaN
1,2023-06-01 01:00:00,28.283333,34.158333,25.866667,0.050000,0.458333,1.000,206.833333,0.0,0.0,...,0.0,NaN,86.916667,0.0,0.0,1.0,202.250000,0.033333,NaN,NaN
2,2023-06-01 02:00:00,27.725000,33.108333,25.841667,0.100000,0.250000,1.000,231.666667,0.0,0.0,...,0.0,NaN,89.583333,0.0,0.0,1.0,226.416667,0.000000,NaN,NaN
3,2023-06-01 03:00:00,27.241667,31.600000,25.191667,0.275000,0.675000,1.525,244.416667,0.0,0.0,...,0.0,NaN,88.666667,0.0,0.0,1.0,248.916667,0.183333,NaN,NaN
4,2023-06-01 04:00:00,27.633333,31.133333,23.716667,0.608333,1.125000,3.100,246.666667,0.0,0.0,...,0.0,NaN,79.416667,0.0,0.0,1.0,245.500000,0.716667,NaN,NaN

In [ ]:
#Dropping relative pressure coz most of the values are missing
hourly_df.drop("Relative Pressure (hPa)", axis=1, inplace=True)

In [ ]:
#Dropping Indoor Battery, Absolute Pressure (hPa) coz most of the values are missing
hourly_df.drop(["Indoor Battery", "Absolute Pressure (hPa)"], axis=1, inplace=True)

In [ ]:
hourly_df.columns

Index(['Datetime', 'Outdoor Temperature (°C)', 'Feels Like (°C)',
       'Dew Point (°C)', 'Wind Speed (m/sec)', 'Wind Gust (m/sec)',
       'Max Daily Gust (m/sec)', 'Wind Direction (°)', 'Hourly Rain (mm/hr)',
       'Event Rain (mm)', 'Daily Rain (mm)', 'Weekly Rain (mm)',
       'Monthly Rain (mm)', 'Yearly Rain (mm)', 'Humidity (%)',
       'Ultra-Violet Radiation Index', 'Solar Radiation (W/m^2)',
       'Outdoor Battery', 'Avg Wind Direction (10 mins) (°)',
       'Avg Wind Speed (10 mins) (m/sec)'],
      dtype='object')

In [ ]:
hourly_df.to_csv(
    "cleaned_june_weather.csv",
    index=False,
    float_format="%.2f"
)

In [ ]:
from google.colab import files
files.download("cleaned_june_weather.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
file_path = '/content/drive/MyDrive/team_lambda/cleaned_june_weather.csv'

hourly_df.to_csv(file_path, index=False)

print("File saved successfully!")

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

# df.to_csv(
#     "/content/drive/MyDrive/team_lambda/cleaned_hourly_may1.csv",
#     index=False
# )
# print("Cleaned CSV saved to Google Drive")

In [ ]:
hourly_df["Datetime"].head()

In [ ]:
# Check for duplicate timestamps
hourly_df.duplicated(subset=["Datetime"]).sum()

In [ ]:
hourly_df.describe()

In [ ]:
#missing values
hourly_df.isna().sum()

In [ ]:
# hourly_df["hour"] = hourly_df["Datetime"].dt.hour
# hourly_df["day"] = hourly_df["Datetime"].dt.day
# hourly_df["month"] = hourly_df["Datetime"].dt.month
# hourly_df["day_of_week"] = hourly_df["Datetime"].dt.dayofweek

In [ ]:
print(hourly_df.columns.tolist())

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Better visuals
plt.style.use("seaborn-v0_8")
sns.set_context("talk")

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    "/content/drive/MyDrive/team_lambda/cleaned_hourly_may1.csv"
)


# Convert datetime column (adjust name if needed)
df["Datetime"] = pd.to_datetime(df["Datetime"])

# Set datetime as index
df = df.set_index("Datetime")

df.head()

In [ ]:
df.columns

In [ ]:
#Outdoor Temperature
plt.figure(figsize=(15,5))
plt.plot(df.index, df["Outdoor Temperature (°C)"])
plt.title("Hourly Outdoor Temperature Trend")
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.show()

In [ ]:
#Humidity
plt.figure(figsize=(15,5))
plt.plot(df.index, df["Humidity (%)"], color="green")
plt.title("Hourly Humidity Trend")
plt.xlabel("Time")
plt.ylabel("Humidity (%)")
plt.show()

In [ ]:

#Wind Speed
plt.figure(figsize=(15,5))
plt.plot(df.index, df["Wind Speed (m/sec)"], color="orange")
plt.title("Hourly Wind Speed Trend")
plt.xlabel("Time")
plt.ylabel("Wind Speed (m/sec)")
plt.show()

In [ ]:
#DAILY & MONTHLY PATTERNS (AGGREGATION EDA)

In [ ]:
#Average Temperature by Hour of Day
df["Hour"] = df.index.hour

hourly_avg = df.groupby("Hour")["Outdoor Temperature (°C)"].mean()

plt.figure(figsize=(10,5))
plt.plot(hourly_avg.index, hourly_avg, marker="o")
plt.title("Average Temperature by Hour of Day")
plt.xlabel("Hour of Day")
plt.ylabel("Temperature (°C)")
plt.xticks(range(0,24))
plt.show()

In [ ]:
# DISTRIBUTION ANALYSIS (STATISTICAL EDA)
#Temperature Distribution
plt.figure(figsize=(8,5))
sns.histplot(df["Outdoor Temperature (°C)"], kde=True)
plt.title("Distribution of Outdoor Temperature")
plt.show()

In [ ]:
#Temperature Distribution

plt.figure(figsize=(8,5))
sns.histplot(df["Humidity (%)"], kde=True, color="green")
plt.title("Distribution of Humidity")
plt.show()

In [ ]:
#Wind Speed Distribution
plt.figure(figsize=(8,5))
sns.histplot(df["Wind Speed (m/sec)"], kde=True, color="orange")
plt.title("Distribution of Wind Speed")
plt.show()

In [ ]:
#Temperature Outliers
plt.figure(figsize=(6,4))
sns.boxplot(y=df["Outdoor Temperature (°C)"])
plt.title("Temperature Outliers")
plt.show()

In [ ]:
#Humidity Outliers
plt.figure(figsize=(6,4))
sns.boxplot(y=df["Humidity (%)"], color="green")
plt.title("Humidity Outliers")
plt.show()

In [ ]:
#
plt.figure(figsize=(6,4))
sns.boxplot(y=df["Wind Speed (m/sec)"], color="orange")
plt.title("Wind Speed Outliers")
plt.show()

In [ ]:
##ROLLING STATISTICS (ADVANCED TIME-SERIES EDA)

In [ ]:

#7-Day Rolling Mean (Temperature)
df["Temp_7D_Rolling"] = df["Outdoor Temperature (°C)"].rolling(24*7).mean()

plt.figure(figsize=(15,5))
plt.plot(df.index, df["Temp_7D_Rolling"], color="purple")
plt.title("7-Day Rolling Average Temperature")
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.show()